[package]
name = "filemind-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
filemind-core = { path = "../core" }
anyhow.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
directories.workspace = true
chrono.workspace = true

[dev-dependencies]
tempfile.workspace = true
chrono.workspace = true
